language: php

php:
  - 7.2
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.2

install: travis_retry composer install --no-interaction --prefer-source

after_success:
  - travis_retry php vendor/bin/coveralls
  #or enable logging
  - travis_retry php vendor/bin/coveralls -v

sudo: required

dist: trusty
addons:
  chrome: stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - cp .env.dusk.local .env.dev
  - php artisan serve > /dev/null 2>&1 &

script:
  - mkdir -p build/logs
  - php artisan dusk
  - php vendor/bin/phpunit -c phpunit.xml